version: '3.3'

services:
  # Database service (internal only, not exposed)
  mongodb:
    image: mongo:4.4  # Use specific version, not latest
    container_name: medical_records_mongo_prod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_medical_records
      MONGO_INITDB_ROOT_PASSWORD: medical_records_mongo_pass_2024
      MONGO_INITDB_DATABASE: medical_records
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    networks:
      - medical_records_network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Backend API service
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.prod
    container_name: medical_records_backend_prod
    restart: always

    environment:
      - MONGODB_URL=mongodb://admin_medical_records:medical_records_mongo_pass_2024@mongodb:27017/medical_records?authSource=admin
      - JWT_SECRET_KEY=your-super-secret-jwt-key-here-change-this-in-production-2024
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30  # Shorter for production
      - PYTHONPATH=/app
      - ENVIRONMENT=production
    volumes:
      - uploads_data:/app/uploads
    ports:
      - "81:8000"
    depends_on:
      - mongodb
    networks:
      - medical_records_network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend.prod
    container_name: medical_records_frontend_prod
    restart: always
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - HOSTNAME=0.0.0.0
    depends_on:
      - backend
    networks:
      - medical_records_network

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongodb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/medical_records/data/mongodb
  uploads_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/medical_records/data/uploads

networks:
  medical_records_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16 