version: '3.3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: medical_records_frontend
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:81
    networks:
      - frontend_network

networks:
  frontend_network:
    driver: bridge 