services:
  mongodb:
    image: mongo:latest
    container_name: medical_records_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: medical_records
    volumes:
      - mongodb_data:/data/db
    networks:
      - medical_records_network

  mongo-express:
    image: mongo-express:latest
    container_name: medical_records_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: adminpassword
      ME_CONFIG_MONGODB_URL: mongodb://admin:adminpassword@mongodb:27017/
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - medical_records_network

  api:
    build: ./api
    container_name: medical_records_api
    restart: unless-stopped
    ports:
      - "81:8000"
    environment:
      MONGODB_URL: mongodb://admin:adminpassword@mongodb:27017/medical_records?authSource=admin
      JWT_SECRET_KEY: your-super-secret-jwt-key-change-this-in-production
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1000
    volumes:
      - ./api/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - medical_records_network

volumes:
  mongodb_data:
    driver: local

networks:
  medical_records_network:
    driver: bridge 